[package]
name = "fetchlogs"
version = "0.2.0"
authors = ["James Graham <james@hoppipolla.co.uk>"]
readme = "readme.md"

[dependencies]
clap = "2"
regex = "1"
reqwest = "0.9"
scoped_threadpool = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"